server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.97.11.99:3306/xixiframe?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true
    username: root
    password: P4WH+-@751YU5K7NB1JUR1aDT3BQE

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*.xml

logging:
  level:
    root: info
    org.springframework.web: ERROR
    com.your.package: DEBUG

---
spring:
  redis:
    # 地址
    host: 47.97.11.99
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 2
    # 密码
    password: F^GX9svKX7elVUi9
    # 连接超时时间
    timeout: 10s
    # 是否开启ssl
    ssl: false

avatarImagesFilePath: D://local//XixiFrame//uploadPath//userAvatar//
